[package]
name = "torchlings"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4"
colored = "2.1"
walkdir = "2.4"
anyhow = "1.0"
rayon = "1.10"
crossbeam = "0.8"
indicatif = "0.17"
num_cpus = "1.10"